In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [2]:
model = nn.Sequential([
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,1),
    nn.Sigmoid()
])

In [3]:
input_data = np.array([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]])
target_data = np.array([[0],[0],[1],[1]])
input = FloatTensor([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]], autograd=True)
target = FloatTensor([[0],[0],[1],[1]], autograd=True)

In [4]:
pred = model(input)
#loss = (pred - target) ** 2
#loss.backward()

In [5]:
pred

[[ 0.7043499]
 [ 0.7426865]
 [ 0.7711535]
 [ 0.7993531]]
[syft.FloatTensor:10 grad:None size:4x1]

	-----------creators-----------
	[syft.FloatTensor:9 grad:None size:4x1]
	------------------------------



In [6]:
# Testing MSELoss: 
loss = (nn.MSELoss()).forward(pred,target)
print(loss)
print(((pred-target)**2).sum())

  1.140322 

  1.140322 



In [6]:
#Manual Cross Entropy Calc: 
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)
print(pred.to_numpy())
print(softmax(pred.to_numpy()))
-1*np.sum(target_data*np.log1p(softmax(pred.to_numpy())))

[[ 0.7043499]
 [ 0.7426865]
 [ 0.7711535]
 [ 0.7993531]]
[[ 0.23765225]
 [ 0.24693993]
 [ 0.25407058]
 [ 0.26133724]]


-0.45856718401967267

In [7]:
# Testing Cross Entropy Loss
loss = (nn.CrossEntropyLoss()).forward(pred,target)
print(loss)

 -1.386294 

   0.7043499 
   0.7426865 
   0.7711535 
   0.7993531  



Just testing the printing works: 

In [8]:
model

<syft.nn.linear at 1>
	 W:[syft.FloatTensor:1 grad:None size:3x4]
	 A:[syft.FloatTensor:7 grad:None size:4x4]

<syft.nn.sigmoid at 2>
	 A:[syft.FloatTensor:8 grad:None size:4x4]

<syft.nn.linear at 3>
	 W:[syft.FloatTensor:3 grad:None size:4x1]
	 A:[syft.FloatTensor:9 grad:None size:4x1]

<syft.nn.sigmoid at 4>
	 A:[syft.FloatTensor:10 grad:None size:4x1]
