In [1]:
import syft
import syft.nn as nn

import imp
imp.reload(syft)
imp.reload(syft.nn)

import numpy as np
from syft import FloatTensor

/home/david/code/OpenMined/openmined_env/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
syft.set_seed(0) # Setting seed to 0 turns off any previously activated random seed
model = nn.Sequential([
    nn.Linear(250,100, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(100,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,200, initializer="Xavier"),
    nn.Sigmoid()
])
parameters = []
for parameter in model.parameters():
    if parameter.shape()[0] != 1:
        parameters.append(parameter.to_numpy())
model = nn.Sequential([
    nn.Linear(250,100, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(100,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,200, initializer="Xavier"),
    nn.Sigmoid()
])
parameters2 = []
for parameter in model.parameters():
    if parameter.shape()[0] !=1:
        parameters2.append(parameter.to_numpy())
        
print("Sum of absolute difference per parameter")
for p1, p2 in zip(parameters, parameters2):
    print(np.sum(np.abs(p1 - p2)))
print("Average absolute difference using syft.random() {}"\
      .format(np.sum(np.abs(syft.random(100,10).to_numpy() - syft.random(100,10).to_numpy()))/1000.0))
print("Average absolute difference using syft.randn() {}"\
      .format(np.sum(np.abs(syft.randn(100,10).to_numpy() - syft.randn(100,10).to_numpy()))/1000.0))

Sum of absolute difference per parameter
1057.78273364
332.753012518
238.117063261
931.93597974
Average absolute difference using syft.random() 0.33985596813589997
Average absolute difference using syft.randn() 1.15106533576001


In [4]:
print("Parameters model 1")
print(parameters[0][0:3,0:3])

print("Parameters model 2")
print(parameters2[0][0:3,0:3])

print("\nrandom generated numbers")
print(syft.random(3,3).to_numpy())
print("random generated numbers")
print(syft.random(3,3).to_numpy())

Parameters model 1
[[-0.03263339 -0.04554856 -0.05024899]
 [ 0.04565185 -0.04313135 -0.03211186]
 [ 0.05663639 -0.00955244 -0.0624229 ]]
Parameters model 2
[[-0.00256749 -0.06185    -0.03395993]
 [ 0.03186226 -0.01380227  0.0389542 ]
 [-0.03664888  0.02250374  0.06318238]]

random generated numbers
[[ 0.4536183  0.3163836  0.3438403]
 [ 0.3064705  0.2716374  0.511596 ]
 [ 0.1366993  0.9746667  0.9886935]]
random generated numbers
[[ 0.5323028  0.7524583  0.3155937]
 [ 0.2183477  0.2264375  0.5325262]
 [ 0.0138793  0.9350786  0.3100049]]


# Now setting the random seed to 123

In [5]:
syft.set_seed(123)
model = nn.Sequential([
    nn.Linear(250,100, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(100,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,200, initializer="Xavier"),
    nn.Sigmoid()
])
parameters = []
for parameter in model.parameters():
    if parameter.shape()[0] != 1:
        parameters.append(parameter.to_numpy())
model = nn.Sequential([
    nn.Linear(250,100, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(100,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,50, initializer="Xavier"),
    nn.Tanh(),
    nn.Linear(50,200, initializer="Xavier"),
    nn.Sigmoid()
])
parameters2 = []
for parameter in model.parameters():
    if parameter.shape()[0] !=1:
        parameters2.append(parameter.to_numpy())
        
print("Sum of absolute difference per parameter")
for p1, p2 in zip(parameters, parameters2):
    print(np.sum(np.abs(p1 - p2)))
print("Average absolute difference using syft.random() {}"\
      .format(np.sum(np.abs(syft.random(100,10).to_numpy() - syft.random(100,10).to_numpy()))/1000.0))
print("Average absolute difference using syft.randn() {}"\
      .format(np.sum(np.abs(syft.randn(100,10).to_numpy() - syft.randn(100,10).to_numpy()))/1000.0))

Sum of absolute difference per parameter
0.0
0.0
0.0
0.0
Average absolute difference using syft.random() 0.0
Average absolute difference using syft.randn() 0.0


In [6]:
print("Parameters model 1")
print(parameters[0][0:3,0:3])

print("Parameters model 2")
print(parameters2[0][0:3,0:3])

print("\nrandom generated numbers")
print(syft.random(3,3).to_numpy())
print("random generated numbers")
print(syft.random(3,3).to_numpy())

Parameters model 1
[[-0.01261038 -0.01589158 -0.03097501]
 [ 0.0461694   0.00037401  0.01462568]
 [-0.05269117  0.04107428 -0.0498594 ]]
Parameters model 2
[[-0.01261038 -0.01589158 -0.03097501]
 [ 0.0461694   0.00037401  0.01462568]
 [-0.05269117  0.04107428 -0.0498594 ]]

random generated numbers
[[ 0.5996938   0.625634    0.7448789 ]
 [ 0.2736391   0.3258087   0.9293917 ]
 [ 0.07169164  0.656182    0.1452859 ]]
random generated numbers
[[ 0.5996938   0.625634    0.7448789 ]
 [ 0.2736391   0.3258087   0.9293917 ]
 [ 0.07169164  0.656182    0.1452859 ]]
