In [1]:
%load_ext autoreload
%autoreload 2

import syft
import syft.nn as nn
import syft.grid.grid as grid
import imp
imp.reload(syft)
imp.reload(syft.nn)
imp.reload(syft.grid)

import numpy as np
from syft import FloatTensor
from syft import IntTensor

/Users/atrask/anaconda/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
model = nn.Sequential([
    nn.Linear(3,1)
])

g = grid.Grid()

config1 = g.configuration(
    model=model,
    lr=0.01,
    criterion='mseloss',
    iters=200
)

config2 = g.configuration(
    model=model,
    lr=0.1,
    criterion='cross_entropy_loss',
    iters=500
)

config3 = g.configuration(
    model=model,
    lr=0.1,
    criterion='mseloss',
    iters=200
)

In [3]:
input = FloatTensor([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]], autograd=True)
target = FloatTensor([[0],[0],[1],[1]], autograd=True)

g.learn(
  input = input,
  target = target,
  configurations = [config1, config2, config3],
  name='MNIST'
)

In [6]:
g = grid.Grid()
g.get_experiments()

 ALL EXPERIMENTS 
Get the result of your experiment by calling get_results with the highlighted uuid

    - MNIST (89af0143-c84d-4e51-af09-577081183815)
    - Experiment on 24-1-2018 (f6920bdf-53fb-402a-92a1-96599c0ae90b)


In [7]:
r = g.get_results('2fa36572-ee86-4bef-9075-87bc52694c1d')

AttributeError: 'Grid' object has no attribute 'jobId'

In [10]:
m1 = r.results[0]
m2 = r.results[1]
m3 = r.results[2]

In [11]:
m1.forward(input)

[[ 0.3708287]
 [ 0.4668186]
 [ 1.144389 ]
 [ 1.240379 ]]
[syft.FloatTensor:124008 grad:None size:4x1 c:[] p:[109716, 117161] init:mm]

	-----------creators-----------
	[syft.FloatTensor:109716 grad:None size:4x3 c:[124008] p:[] init:]
	[syft.FloatTensor:117161 grad:None size:3x1 c:[124008] p:[] init:]
	------------------------------



In [15]:
m2.forward(input)

[[ 0.2955911]
 [ 0.2075086]
 [-0.1233788]
 [-0.2114614]]
[syft.FloatTensor:12028 grad:None size:4x1 c:[] p:[1157, 12025] init:mm]

	-----------creators-----------
	[syft.FloatTensor:1157 grad:None size:4x3 c:[12027, 12028] p:[] init:]
	[syft.FloatTensor:12025 grad:None size:3x1 c:[12028] p:[] init:]
	------------------------------



In [16]:
m3.forward(input)

[[-0.7046605]
 [-0.4219377]
 [ 0.8801706]
 [ 1.162893 ]]
[syft.FloatTensor:12029 grad:None size:4x1 c:[] p:[1157, 12026] init:mm]

	-----------creators-----------
	[syft.FloatTensor:1157 grad:None size:4x3 c:[12027, 12028, 12029] p:[] init:]
	[syft.FloatTensor:12026 grad:None size:3x1 c:[12029] p:[] init:]
	------------------------------

