In [1]:
# from http://iamtrask.github.io/2015/07/12/basic-python-network/

import numpy as np
import time

In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_interpolated(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    
    W0  = 0.5
    W1  = 0.2159198  #015))
    W3  = -0.0082176 #259))
    W5  = 0.0001825  #597))
    W7  = -0.0000018 #848))
    W9  = 0.0000000  #072))

    x2 = x * x
    x3 = x2 * x
    x5 = x2 * x3
    x7 = x2 * x5
    x9 = x2 * x7

    return x9 * W9 + x7 * W7 + x5 *W5 + x3 * W3 + x * W1 + W0

In [4]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

In [5]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = (2*np.random.random((3,1)) - 1) / 1000

print(syn0)

[[-0.00016596]
 [ 0.00044065]
 [-0.00099977]]


In [6]:
start_time = time.time()

In [7]:
for iter in range(100):

    # forward propagation
    l0 = X
    l1 = sigmoid_interpolated(np.dot(l0,syn0))
    #np.maximum(l1, 0, l1)
    
    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * sigmoid_interpolated(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)

In [8]:
print("Elapsed Training Time:\n", time.time() - start_time)

Elapsed Training Time:
 0.021358013153076172


In [9]:
print ("Output After Training:")
print (l1)
print ("Weights After Training:")
print (syn0)

Output After Training:
[[ 0.40024437]
 [ 0.36081025]
 [ 0.72714857]
 [ 0.6908204 ]]
Weights After Training:
[[ 1.68751916]
 [-0.20658497]
 [-0.52495068]]


In [10]:
predictions = sigmoid_interpolated(np.dot(X,syn0))
print("Predictions:")
print(predictions)

Predictions:
[[ 0.38783428]
 [ 0.34522594]
 [ 0.73849175]
 [ 0.69938064]]
