# OpenMined Arsenal Showcase

So, we are using our [great Unity backend](https://github.com/OpenMined/OpenMined/blob/master/tutorials/WhyUnity.md) to do all the heavy stuff.

Let's see what it can actually do!

![OM_Arsenal](https://github.com/OpenMined/OpenMined/blob/master/images/OM_Arsenal.png)

## Imports

In [2]:
import syft
import syft.nn as nn
import syft.controller
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor
import math

## Arsenal

### Abs

In [3]:
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)

In [4]:
a.abs()

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor of size 6]

### Addmm

In [12]:
x = np.array([ [0,0,1],[1,1,1],[1,0,1],[0,1,1] ])
y = np.array([[0,1,1,0]]).T
w_initial = 2*np.random.random((len(x[0]),len(y[0]))) - 1
zeros_np = np.array([[0,0,0,0]]).T

print('X:\n',x)
print('W:\n',w_initial)
print('Zeros:\n',zeros_np)

X = FloatTensor(x)
W = FloatTensor(w_initial)
zeros = FloatTensor(zeros_np)

X:
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
W:
 [[-0.37839389]
 [ 0.15115471]
 [ 0.36190698]]
Zeros:
 [[0]
 [0]
 [0]
 [0]]


In [13]:
zeros.addmm(X,W)

[[ 0.361907  ]
 [ 0.1346678 ]
 [-0.01648691]
 [ 0.5130617 ]]
[syft.FloatTensor of size 4x1]

### Copy

In [14]:
a = FloatTensor(np.array([1,2,3]))

In [15]:
a.copy()

[ 1.  2.  3.]
[syft.FloatTensor of size 3]

### Cos

In [6]:
a = FloatTensor(np.array([45,90,180,365,math.pi,math.pi*2]))

In [10]:
a.cos()

43
FloatTensor.__init__: 43


0,525322,	-0,4480736,	-0,5984601,	0,8390551,	-1,	1,	


### Cosh

In [11]:
a = FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 44
SyftController.processMessage: Command not found.


In [12]:
a.cosh()

45
FloatTensor.__init__: 45


3,762196,	1,543081,	1,	1,543081,	3,762196,	


### Delete

In [13]:
a = FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 46
SyftController.processMessage: Command not found.


In [14]:
a.delete_tensor()

SyftController.processMessage: Command not found.


### Floor_

In [15]:
a = FloatTensor(np.array([0.5,1.1,2.9,3.4]))

FloatTensor.__init__: 47


In [16]:
a.floor_()

47
0,	1,	2,	3,	




0,	1,	2,	3,	


### Is contiguous

In [17]:
a = FloatTensor(np.array([0.5,1.1,2.9,3.4]))

FloatTensor.__init__: 48


In [18]:
a.is_contiguous()

True


'True'

### Neg

In [19]:
a = FloatTensor(np.array([1,-2,3,-4]))

FloatTensor.__init__: 49
SyftController.processMessage: Command not found.


In [20]:
a.neg()

50
FloatTensor.__init__: 50


-1,	2,	-3,	4,	


### Rsqrt

In [21]:
a = FloatTensor(np.array([-2,-1,0,1,2,16,49,121,250]))

FloatTensor.__init__: 51
SyftController.processMessage: Command not found.


In [22]:
a.rsqrt()

52
FloatTensor.__init__: 52


NaN,	NaN,	Infinito,	1,	0,7071068,	0,25,	0,1428571,	0,09090909,	0,06324556,	


### Sigmoid_

In [7]:
a = FloatTensor(np.array([-10,-2,-1,0,1,2,10]))

In [24]:
a.sigmoid_()

sigmoid_: OK
4,539787E-05,	0,1192029,	0,2689414,	0,5,	0,7310586,	0,8807971,	0,9999546,	




4,539787E-05,	0,1192029,	0,2689414,	0,5,	0,7310586,	0,8807971,	0,9999546,	


### Sinh

In [25]:
a = FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 54


In [26]:
a.sinh()

55
FloatTensor.__init__: 55


-3,62686,	-1,175201,	0,	1,175201,	3,62686,	


### Sqrt

In [27]:
a = FloatTensor(np.array([-2,-1,0,1,2,16,49,121,250]))

FloatTensor.__init__: 56
SyftController.processMessage: Command not found.


In [28]:
a.sqrt()

57
FloatTensor.__init__: 57


NaN,	NaN,	0,	1,	1,414214,	4,	7,	11,	15,81139,	


### Tanh

In [29]:
a = FloatTensor(np.array([-10,-2,-1,0,1,2,10]))

FloatTensor.__init__: 58
SyftController.processMessage: Command not found.


In [30]:
a.tanh()

59
FloatTensor.__init__: 59


-1,	-0,9640276,	-0,7615942,	0,	0,7615942,	0,9640276,	1,	


### Triu

In [31]:
a = FloatTensor(np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4))

FloatTensor.__init__: 60
SyftController.processMessage: Command not found.


In [32]:
a.triu(k=0)

61
FloatTensor.__init__: 61


1,	2,	3,	4,	
0,	6,	7,	8,	
0,	0,	11,	12,	
0,	0,	0,	16,	


### Trunc

In [33]:
a = FloatTensor(np.array([1.2,2.3,3.4,120.9]))

FloatTensor.__init__: 62
SyftController.processMessage: Command not found.


In [34]:
a.trunc()

63
FloatTensor.__init__: 63


1,	2,	3,	120,	


### Zero_

In [9]:
a = FloatTensor(np.array([1.2,2.3,3.4,120.9]))

In [10]:
a.zero_()

[ 0.  0.  0.  0.]
[syft.FloatTensor of size 4]

### Squeeze

In [11]:
a = FloatTensor(np.ones([2, 1, 2]))
a.squeeze()

KeyboardInterrupt: 