In [27]:
import syft
import syft.nn as nn
import syft.controller
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [28]:
model = nn.Sequential([
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,1),
    nn.Sigmoid()
])

In [29]:
model

In [30]:
m = model.models()
m

In [31]:
p = model.parameters()
p

[[[ 0.9993694   0.5485256   0.3619677  -0.07908762]
  [ 0.1888548   0.5695789   0.8287675  -0.7252917 ]
  [-0.4862165   0.1122268   0.5645595  -0.342375  ]]
 [syft.FloatTensor:62 grad:None size:3x4], [[ 0.9993694 ]
  [ 0.5485256 ]
  [ 0.3619677 ]
  [-0.07908762]]
 [syft.FloatTensor:64 grad:None size:4x1]]

In [32]:
input = FloatTensor([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]], autograd=True)
target = FloatTensor([[0],[0],[1],[1]], autograd=True)

In [33]:
pred = model(input)

In [35]:
model.parameters()

[[[ 0.9993694   0.5485256   0.3619677  -0.07908762]
  [ 0.1888548   0.5695789   0.8287675  -0.7252917 ]
  [-0.4862165   0.1122268   0.5645595  -0.342375  ]]
 [syft.FloatTensor:62 grad:None size:3x4]
 
 	-----------children-----------
 	[syft.FloatTensor:72 grad:None size:4x4]
 	------------------------------
 
 , [[ 0.9993694 ]
  [ 0.5485256 ]
  [ 0.3619677 ]
  [-0.07908762]]
 [syft.FloatTensor:64 grad:None size:4x1]
 
 	-----------children-----------
 	[syft.FloatTensor:74 grad:None size:4x1]
 	------------------------------
 
 ]

In [18]:
loss = pred

In [19]:
loss.backward()

In [20]:
input

[[ 0.  0.  1.]
 [ 0.  1.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  1.]]
[syft.FloatTensor:9 grad:31 size:4x3]

	-----------children-----------
	[syft.FloatTensor:11 grad:28 size:4x4]
	------------------------------



In [21]:
loss

[[ 0.7043499]
 [ 0.7426865]
 [ 0.7711535]
 [ 0.7993531]]
[syft.FloatTensor:14 grad:15 size:4x1]

	-----------creators-----------
	[syft.FloatTensor:13 grad:20 size:4x1]
	------------------------------



In [24]:
x = syft.controller.get_tensor(13)

In [25]:
x

[[ 0.8680987]
 [ 1.059979 ]
 [ 1.214836 ]
 [ 1.382256 ]]
[syft.FloatTensor:13 grad:20 size:4x1]

	-----------children-----------
	[syft.FloatTensor:14 grad:15 size:4x1]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:12 grad:23 size:4x4]
	[syft.FloatTensor:3 grad:37 size:4x1]
	------------------------------



In [23]:
# Example of error handling
input + target

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-c73fac42678d>", line 2, in <module>
    input + target
  File "/Users/atrask/anaconda/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/tensor.py", line 88, in __add__
    return self.arithmetic_operation(x, "add", False)
  File "/Users/atrask/anaconda/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/tensor.py", line 405, in arithmetic_operation
    self.cmd(operation_cmd, [parameter]))  # sends the command
  File "/Users/atrask/anaconda/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/controller.py", line 85, in send_json
    raise Exception(res)
Exception: Unity Error: System.InvalidOperationException: Tensors cannot be added since they have different sizes: 4 != 12
  at OpenMined.Syft.Tensor.FloatTensor.SameSizeDimensionsShapeAndLocation (Op

Exception: Unity Error: System.InvalidOperationException: Tensors cannot be added since they have different sizes: 4 != 12
  at OpenMined.Syft.Tensor.FloatTensor.SameSizeDimensionsShapeAndLocation (OpenMined.Syft.Tensor.FloatTensor& tensor) [0x00035] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Helpers.cs:13 
  at OpenMined.Syft.Tensor.FloatTensor.Add (OpenMined.Syft.Tensor.FloatTensor x, System.Boolean inline) [0x00043] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs:48 
  at OpenMined.Syft.Tensor.FloatTensor.ProcessMessage (OpenMined.Network.Utils.Command msgObj, OpenMined.Network.Controllers.SyftController ctrl) [0x006c9] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs:197 
  at OpenMined.Network.Controllers.SyftController.processMessage (System.String json_message) [0x0012e] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs:120 