In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [2]:
model = nn.Sequential([
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,1),
    nn.Sigmoid()
])

In [3]:
model

<syft.nn.linear at 61>
	 W:[syft.FloatTensor:232 grad:None size:3x4]
<syft.nn.sigmoid at 62>
<syft.nn.linear at 63>
	 W:[syft.FloatTensor:234 grad:None size:4x1]
<syft.nn.sigmoid at 64>

In [4]:
m = model.models()
m

[<syft.nn.linear at 61>
 	 W:[syft.FloatTensor:232 grad:None size:3x4],
 <syft.nn.sigmoid at 62>,
 <syft.nn.linear at 63>
 	 W:[syft.FloatTensor:234 grad:None size:4x1],
 <syft.nn.sigmoid at 64>]

In [5]:
p = model.parameters()
p

[[[ 0.9993694   0.5485256   0.3619677  -0.07908762]
  [ 0.1888548   0.5695789   0.8287675  -0.7252917 ]
  [-0.4862165   0.1122268   0.5645595  -0.342375  ]]
 [syft.FloatTensor:232 grad:None size:3x4], [[ 0.9993694 ]
  [ 0.5485256 ]
  [ 0.3619677 ]
  [-0.07908762]]
 [syft.FloatTensor:234 grad:None size:4x1]]

In [6]:
input = FloatTensor([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]], autograd=True)
target = FloatTensor([[0],[0],[1],[1]], autograd=True)

In [7]:
pred = model(input)

In [8]:
model

<syft.nn.linear at 61>
	 W:[syft.FloatTensor:232 grad:None size:3x4]
	 A:[syft.FloatTensor:250 grad:None size:4x4]

<syft.nn.sigmoid at 62>
	 A:[syft.FloatTensor:251 grad:None size:4x4]

<syft.nn.linear at 63>
	 W:[syft.FloatTensor:234 grad:None size:4x1]
	 A:[syft.FloatTensor:252 grad:None size:4x1]

<syft.nn.sigmoid at 64>
	 A:[syft.FloatTensor:253 grad:None size:4x1]


In [9]:
tensors[92]

[[ 0.3807853  0.5280273  0.6375068  0.4152327]
 [ 0.4262026  0.6641416  0.8011228  0.2558471]
 [ 0.6255453  0.6594294  0.7163702  0.3961668]
 [ 0.6686327  0.7738765  0.8526193  0.2410824]]
[syft.FloatTensor:92 grad:120 size:4x4]

	-----------children-----------
	[syft.FloatTensor:93 grad:118 size:4x1]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:91 grad:125 size:4x4]
	------------------------------



In [10]:
models[64]

<syft.nn.sigmoid at 64>
	 A:[syft.FloatTensor:253 grad:None size:4x1]


In [11]:
loss = pred

In [12]:
loss.backward()

In [13]:
model

<syft.nn.linear at 61>
	 W:[syft.FloatTensor:232 grad:290 size:3x4]
	 A:[syft.FloatTensor:250 grad:286 size:4x4]

<syft.nn.sigmoid at 62>
	 A:[syft.FloatTensor:251 grad:281 size:4x4]

<syft.nn.linear at 63>
	 W:[syft.FloatTensor:234 grad:292 size:4x1]
	 A:[syft.FloatTensor:252 grad:279 size:4x1]

<syft.nn.sigmoid at 64>
	 A:[syft.FloatTensor:253 grad:274 size:4x1]


In [14]:
# Example of error handling
input + target

Exception: Unity Error: System.InvalidOperationException: Tensors cannot be added since they have different sizes: 4 != 12
  at OpenMined.Syft.Tensor.FloatTensor.SameSizeDimensionsShapeAndLocation (OpenMined.Syft.Tensor.FloatTensor& tensor) [0x00035] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Helpers.cs:13 
  at OpenMined.Syft.Tensor.FloatTensor.Add (OpenMined.Syft.Tensor.FloatTensor x, System.Boolean inline) [0x00043] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs:48 
  at OpenMined.Syft.Tensor.FloatTensor.ProcessMessage (OpenMined.Network.Utils.Command msgObj, OpenMined.Network.Controllers.SyftController ctrl) [0x006da] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs:197 
  at OpenMined.Network.Controllers.SyftController.processMessage (System.String json_message) [0x0012e] in /Users/atrask/Laboratory/openmined/OpenMined/UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs:120 