In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor
import torch
from torch.autograd import Variable

In [ ]:
x = FloatTensor([[1,1,1,1]],autograd=True).view(1,4,1)

In [ ]:
y = x.expand(2,4,2).contiguous()

In [29]:
y.backward()

In [24]:
x.grad()

[[[ 4.]
  [ 4.]
  [ 4.]
  [ 4.]]]
[syft.FloatTensor:16 grad:None size:1x4x1 c:[17] p:[15] init:view_1_4_1]

	-----------children-----------
	[syft.FloatTensor:17 grad:None size:1x4 c:[] p:[16] init:view_1_4]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:15 grad:None size:1x4 c:[16] p:[14] init:sum_2]
	------------------------------



In [27]:
x = x.grad().view(1,4)

In [31]:
x.to_numpy()

array([[ 2.,  2.,  2.,  2.]])

In [3]:
y = x.expand(5,2)

In [4]:
z = y.contiguous()

In [5]:
z

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]]
[syft.FloatTensor:4 grad:None size:5x2 c:[] p:[3] init:contiguous]

	-----------creators-----------
	[syft.FloatTensor:3 grad:None size:5x2 c:[4] p:[2] init:expand]
	------------------------------



In [8]:
z.sum(0)

[ 15.  15.]
[syft.FloatTensor:5 grad:None size:2 c:[] p:[4] init:sum_0]

	-----------creators-----------
	[syft.FloatTensor:4 grad:None size:5x2 c:[5, 6] p:[3] init:contiguous]
	------------------------------



In [ ]:
z.view()