# OpenMined Arsenal Showcase

So, we are using our [great Unity backend](https://github.com/OpenMined/OpenMined/blob/master/tutorials/WhyUnity.md) to do all the heavy stuff.

Let's see what it can actually do!

![OM_Arsenal](OpenMined\images\OM_Arsenal.png)

## Imports

In [1]:
import syft.syft as syft
import imp
imp.reload(syft)
from syft.syft import FloatTensor, SyftController
import numpy as np
import math

## Connection

In [2]:
# connect -- rerun this block if you make changes to the unity back-end
#         -- the controller is not yet smart enough to retry connection
#         -- on its own
sc = SyftController()

## Arsenal

### Abs

In [3]:
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = sc.FloatTensor(data)

FloatTensor.__init__: 1


In [4]:
a.abs()

FloatTensor.__init__: 2


1,	2,	3,	4,	5,	6,	


### Addmm

In [5]:
x = np.array([ [0,0,1],[1,1,1],[1,0,1],[0,1,1] ])
y = np.array([[0,1,1,0]]).T
w_initial = 2*np.random.random((len(x[0]),len(y[0]))) - 1
zeros_np = np.array([[0,0,0,0]]).T

print('X:\n',x)
print('W:\n',w_initial)
print('Zeros:\n',zeros_np)

X = sc.FloatTensor(x)
W = sc.FloatTensor(w_initial)
zeros = sc.FloatTensor(zeros_np)

X:
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
W:
 [[-0.94046913]
 [-0.84315467]
 [ 0.80059373]]
Zeros:
 [[0]
 [0]
 [0]
 [0]]
FloatTensor.__init__: 3
FloatTensor.__init__: 4
FloatTensor.__init__: 5


In [6]:
zeros.addmm(X,W)

FloatTensor.__init__: 6


0,8005937,	
-0,9830301,	
-0,1398754,	
-0,04256094,	


### Copy

In [7]:
a = sc.FloatTensor(np.array([1,2,3]))

FloatTensor.__init__: 7


In [8]:
a.copy()

FloatTensor.__init__: 8


1,	2,	3,	


### Cos

In [9]:
a = sc.FloatTensor(np.array([45,90,180,365,math.pi,math.pi*2]))

FloatTensor.__init__: 9


In [10]:
a.cos()

FloatTensor.__init__: 10


0,525322,	-0,4480736,	-0,5984601,	0,8390551,	-1,	1,	


### Cosh

In [11]:
a = sc.FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 11


In [12]:
a.cosh()

FloatTensor.__init__: 12


3,762196,	1,543081,	1,	1,543081,	3,762196,	


### Delete

In [13]:
a = sc.FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 13


In [14]:
a.delete_tensor()

### Floor_

In [15]:
a = sc.FloatTensor(np.array([0.5,1.1,2.9,3.4]))

FloatTensor.__init__: 14


In [16]:
a.floor_()

0,	1,	2,	3,	


### Is contiguous

In [17]:
a = sc.FloatTensor(np.array([0.5,1.1,2.9,3.4]))

FloatTensor.__init__: 15


In [18]:
a.is_contiguous()

'True'

### Neg

In [19]:
a = sc.FloatTensor(np.array([1,-2,3,-4]))

FloatTensor.__init__: 16


In [20]:
a.neg()

FloatTensor.__init__: 17


-1,	2,	-3,	4,	


### Sigmoid_

In [21]:
a = sc.FloatTensor(np.array([-10,-2,-1,0,1,2,10]))

FloatTensor.__init__: 18


In [22]:
a.sigmoid_()

4,539787E-05,	0,1192029,	0,2689414,	0,5,	0,7310586,	0,8807971,	0,9999546,	


### Sinh

In [23]:
a = sc.FloatTensor(np.array([-2.0,-1.0,0,1.0,2.0]))

FloatTensor.__init__: 19


In [24]:
a.sinh()

FloatTensor.__init__: 20


-3,62686,	-1,175201,	0,	1,175201,	3,62686,	


### Sqrt

In [25]:
a = sc.FloatTensor(np.array([-2,-1,0,1,2,16,49,121,250]))

FloatTensor.__init__: 21


In [26]:
a.sqrt()

FloatTensor.__init__: 22


NaN,	NaN,	0,	1,	1,414214,	4,	7,	11,	15,81139,	


### Tanh

In [27]:
a = sc.FloatTensor(np.array([-10,-2,-1,0,1,2,10]))

FloatTensor.__init__: 23


In [28]:
a.tanh()

FloatTensor.__init__: 24


-1,	-0,9640276,	-0,7615942,	0,	0,7615942,	0,9640276,	1,	


### Triu

In [29]:
a = sc.FloatTensor(np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4))

FloatTensor.__init__: 25


In [30]:
a.triu(k=0)

FloatTensor.__init__: 26


1,	2,	3,	4,	
0,	6,	7,	8,	
0,	0,	11,	12,	
0,	0,	0,	16,	


### Trunc

In [31]:
a = sc.FloatTensor(np.array([1.2,2.3,3.4,120.9]))

FloatTensor.__init__: 27


In [32]:
a.trunc()

FloatTensor.__init__: 28


1,	2,	3,	120,	


### Zero_

In [33]:
a = sc.FloatTensor(np.array([1.2,2.3,3.4,120.9]))

FloatTensor.__init__: 29


In [34]:
a.zero_()

0,	0,	0,	0,	
