In [88]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

import torch

In [68]:
np.random.seed(1)
a_ = np.array([[1,2,3,4,5],[2,3,4,5,6]]).astype('float')
b_ = np.array([[5,1,3,8,2],[2,5,3,2,5],[3,5,2,3,6]]).astype('float').transpose()

In [89]:
at = Variable(torch.FloatTensor(a_),requires_grad=True)
bt = Variable(torch.FloatTensor(b_),requires_grad=True)
ct = at.sigmoid()

In [63]:
ct

Variable containing:
 1  2
 2  3
 3  4
[torch.FloatTensor of size 3x2]

In [64]:
gt = torch.ones(3,2).cumsum(0).cumsum(1)
gt


 1  2
 2  4
 3  6
[torch.FloatTensor of size 3x2]

In [65]:
ct.backward(gt)
ct.data.numpy()

array([[ 1.,  2.],
       [ 2.,  3.],
       [ 3.,  4.]], dtype=float32)

In [67]:
at.grad

Variable containing:
 1  2  3
 2  4  6
[torch.FloatTensor of size 2x3]

In [20]:
a = FloatTensor(a_,autograd=True)

In [21]:
b = FloatTensor(b_,autograd=True)

In [22]:
grad = FloatTensor(np.ones((2,3)),autograd=False)

In [29]:
c = a.mm(b)

In [30]:
c.backward(grad)

In [31]:
c

[[ 58.  54.  61.]
 [ 77.  71.  80.]]
[syft.FloatTensor:4 grad:3 size:2x3 c:[] p:[1, 2] init:mm]

	-----------creators-----------
	[syft.FloatTensor:1 grad:6 size:2x5 c:[4, 7] p:[] init:]
	[syft.FloatTensor:2 grad:8 size:5x3 c:[4, 5] p:[] init:]
	------------------------------



In [26]:
a.grad()

[[ 10.  11.   8.  13.  13.]
 [ 10.  11.   8.  13.  13.]]
[syft.FloatTensor:6 grad:None size:2x5 c:[] p:[3, 5] init:mm]

	-----------creators-----------
	[syft.FloatTensor:3 grad:None size:2x3 c:[6, 8] p:[] init:]
	[syft.FloatTensor:5 grad:None size:3x5 c:[6] p:[2] init:transpose]
	------------------------------



In [27]:
b.grad()

[[  3.   3.   3.]
 [  5.   5.   5.]
 [  7.   7.   7.]
 [  9.   9.   9.]
 [ 11.  11.  11.]]
[syft.FloatTensor:8 grad:None size:5x3 c:[] p:[7, 3] init:mm]

	-----------creators-----------
	[syft.FloatTensor:7 grad:None size:5x2 c:[8] p:[1] init:transpose]
	[syft.FloatTensor:3 grad:None size:2x3 c:[6, 8] p:[] init:]
	------------------------------



In [28]:
grad

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[syft.FloatTensor:3 grad:None size:2x3 c:[6, 8] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:6 grad:None size:2x5 c:[] p:[3, 5] init:mm]
	[syft.FloatTensor:8 grad:None size:5x3 c:[] p:[7, 3] init:mm]
	------------------------------

