In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

import torch
from torch.autograd import Variable

In [2]:
np.random.seed(1)
a_ = np.array([[1,2,3,4,5],[2,3,4,5,6]]).astype('float')
b_ = np.array([[5,1,3,8,2],[2,5,3,2,5],[3,5,2,3,6]]).astype('float').transpose()

In [3]:
at = Variable(torch.FloatTensor(a_),requires_grad=True)
# bt = Variable(torch.FloatTensor(b_),requires_grad=True)
ct = at.sigmoid()

In [4]:
ct.backward(torch.ones(2,5))
ct.data.numpy()

array([[ 0.7310586 ,  0.88079703,  0.95257413,  0.98201376,  0.99330717],
       [ 0.88079703,  0.95257413,  0.98201376,  0.99330717,  0.99752742]], dtype=float32)

In [5]:
at.grad

Variable containing:
 0.1966  0.1050  0.0452  0.0177  0.0066
 0.1050  0.0452  0.0177  0.0066  0.0025
[torch.FloatTensor of size 2x5]

In [6]:
a = FloatTensor(a_,autograd=True)

In [7]:
grad = FloatTensor(np.ones((2,5)),autograd=False)

In [8]:
c = a.sigmoid()

In [9]:
c.backward(grad)

In [10]:
c

[[ 0.7310586  0.8807971  0.9525741  0.9820138  0.9933072]
 [ 0.8807971  0.9525741  0.9820138  0.9933072  0.9975274]]
[syft.FloatTensor:3 grad:2 size:2x5 c:[4, 7] p:[1] init:sigmoid]

	-----------children-----------
	[syft.FloatTensor:4 grad:None size:2x5 c:[5] p:[3] init:neg]
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[5, 3] init:mul_elem]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:1 grad:8 size:2x5 c:[3] p:[] init:]
	------------------------------



In [11]:
a.grad()

[[ 0.1966119   0.1049936   0.04517666  0.01766273  0.00664803]
 [ 0.1049936   0.04517666  0.01766273  0.00664803  0.00246652]]
[syft.FloatTensor:8 grad:None size:2x5 c:[] p:[7, 2] init:mul_elem]

	-----------creators-----------
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[5, 3] init:mul_elem]
	[syft.FloatTensor:2 grad:None size:2x5 c:[8] p:[] init:]
	------------------------------



In [12]:
grad

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[syft.FloatTensor:2 grad:None size:2x5 c:[8] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:8 grad:None size:2x5 c:[] p:[7, 2] init:mul_elem]
	------------------------------



In [13]:
c = a.sigmoid()

In [14]:
c

[[ 0.7310586  0.8807971  0.9525741  0.9820138  0.9933072]
 [ 0.8807971  0.9525741  0.9820138  0.9933072  0.9975274]]
[syft.FloatTensor:3 grad:2 size:2x5 c:[4, 7] p:[1] init:sigmoid]

	-----------children-----------
	[syft.FloatTensor:4 grad:None size:2x5 c:[5] p:[3] init:neg]
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[5, 3] init:mul_elem]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:1 grad:8 size:2x5 c:[3] p:[] init:]
	------------------------------



In [15]:
c.backward(grad)

In [16]:
c

[[ 0.7310586  0.8807971  0.9525741  0.9820138  0.9933072]
 [ 0.8807971  0.9525741  0.9820138  0.9933072  0.9975274]]
[syft.FloatTensor:3 grad:2 size:2x5 c:[4, 7] p:[1] init:sigmoid]

	-----------children-----------
	[syft.FloatTensor:4 grad:None size:2x5 c:[5] p:[3] init:neg]
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[5, 3] init:mul_elem]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:1 grad:8 size:2x5 c:[3] p:[] init:]
	------------------------------



In [17]:
a.grad()

[[ 0.1966119   0.1049936   0.04517666  0.01766273  0.00664803]
 [ 0.1049936   0.04517666  0.01766273  0.00664803  0.00246652]]
[syft.FloatTensor:8 grad:None size:2x5 c:[] p:[7, 2] init:mul_elem]

	-----------creators-----------
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[5, 3] init:mul_elem]
	[syft.FloatTensor:2 grad:None size:2x5 c:[8] p:[] init:]
	------------------------------

