In [28]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

import torch
from torch.autograd import Variable

In [29]:
np.random.seed(1)
a_ = np.array([[1,2,3,4,5]]).astype('float')
b_ = np.array([[5,1,3,8,2],[2,5,3,2,5],[3,5,2,3,6]]).astype('float').transpose()

In [30]:
at = Variable(torch.FloatTensor(a_),requires_grad=True)
# bt = Variable(torch.FloatTensor(b_),requires_grad=True)
ct = at ** 2

In [31]:
ct.backward(torch.ones(1,5))
ct.data.numpy()

array([[  1.,   4.,   9.,  16.,  25.]], dtype=float32)

In [32]:
at.grad

Variable containing:
  2   4   6   8  10
[torch.FloatTensor of size 1x5]

In [33]:
a = FloatTensor(a_,autograd=True)

In [ ]:
grad = FloatTensor(np.ones((2,5)),autograd=False)

In [ ]:
c = a ** 2

In [ ]:
c.backward(grad)

In [ ]:
c

In [16]:
a.grad()

[[  2.   4.   6.   8.  10.]
 [  4.   6.   8.  10.  12.]]
[syft.FloatTensor:8 grad:None size:2x5 c:[] p:[7, 9] init:mul_scalar]

	-----------creators-----------
	[syft.FloatTensor:7 grad:None size:2x5 c:[8] p:[6, 3] init:mul_elem]
	[syft.FloatTensor:9 grad:None size:1 c:[] p:[] init:]
	------------------------------

