In [2]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

import torch
from torch.autograd import Variable

In [13]:
np.random.seed(1)
a_ = np.array([1,2,3,4,5]).astype('float')
b_ = np.array([5,1,3,8,2]).astype('float')


# # create tensors
# a = FloatTensor(a_, autograd=True)
# b = FloatTensor(b_, autograd=True)
# g = FloatTensor(torch.ones(5).numpy(),autograd=False)

at = Variable(torch.FloatTensor(a_),requires_grad=True)
bt = Variable(torch.FloatTensor(b_),requires_grad=True)
ct = at / 2
ct.backward(torch.ones(5))
ct.data.numpy()

array([ 0.5,  1. ,  1.5,  2. ,  2.5], dtype=float32)

In [15]:
at.grad

Variable containing:
 0.5000
 0.5000
 0.5000
 0.5000
 0.5000
[torch.FloatTensor of size 5]

In [6]:
# bt.grad

In [20]:
ct

Variable containing:
 0.2000
 2.0000
 1.0000
 0.5000
 2.5000
[torch.FloatTensor of size 5]

In [8]:
syft.controller.new_tensors_allowed(False)

False

In [10]:
c = a + b
c.backward(g)
c

[  6.   3.   6.  13.   7.]
[syft.FloatTensor:10 grad:9 size:5 c:[] p:[7, 8] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:7 grad:9 size:5 c:[10] p:[] init:]
	[syft.FloatTensor:8 grad:9 size:5 c:[10] p:[] init:]
	------------------------------



In [11]:
syft.controller.new_tensors_allowed(True)

True

In [12]:
a.grad()

[ 1.  1.  1.  1.  1.]
[syft.FloatTensor:9 grad:None size:5 c:[] p:[] init:]

In [13]:
b.grad()

[ 1.  1.  1.  1.  1.]
[syft.FloatTensor:9 grad:None size:5 c:[] p:[] init:]