In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [12]:
# create tensors
data = np.array([[-1,-2,3,4,5,-6]]).astype('float')
a = FloatTensor(data, autograd=True)
b = FloatTensor(data+5, autograd=True)

In [13]:
np.random.seed(1)
a_ = np.array([[1,2,3,4,5]]).astype('float')
b_ = np.array([[5,1,3,8,2],[2,5,3,2,5],[3,5,2,3,6]]).astype('float').transpose()

In [14]:
at = Variable(torch.FloatTensor(a_),requires_grad=True)
# bt = Variable(torch.FloatTensor(b_),requires_grad=True)
ct = at ** 2

In [18]:
ct.backward(torch.ones(1,5))
ct.data.numpy()

[[ 0.07142857  0.07142857  0.07142857  0.07142857  0.07142857  0.07142857]]
[syft.FloatTensor:17 grad:None size:1x6]

In [19]:
at.grad

[[ 1.  1.  1.  1.  1.  1.]]
[syft.FloatTensor:16 grad:None size:1x6]

In [33]:
a = FloatTensor(a_,autograd=True)

In [20]:
a.grad()

[[ 0.07692308  0.07692308  0.07692308  0.07692308  0.07692308  0.07692308]]
[syft.FloatTensor:18 grad:None size:1x6]