In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)
b = FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 
d = FloatTensor(np.random.rand(2,6))

In [3]:
ds = d.softmax(1)
ds

[[ 0.1155953  0.1493147  0.1060038  0.2188982  0.1551468  0.2550411]
 [ 0.1393843  0.2922336  0.1328941  0.133417   0.1640442  0.1380268]]
[syft.FloatTensor:5 grad:None size:2x6 c:[] p:[4] init:softmax-1]

	-----------creators-----------
	[syft.FloatTensor:4 grad:None size:2x6 c:[5, 5] p:[] init:]
	------------------------------



In [4]:
ds.sample(1)

[0 0]
[syft.IntTensor:1 size:2]

In [13]:
samples = list()
for i in range(100):
    samples.append(ds.sample(1))
    
cnts = np.zeros((2,6))
for s in samples:
    for i,x in enumerate(s.to_numpy()):
        cnts[i][x] += 1
        
cnts / 100

array([[ 0.1 ,  0.2 ,  0.08,  0.23,  0.18,  0.21],
       [ 0.21,  0.3 ,  0.11,  0.12,  0.14,  0.12]])

In [15]:
b

[[-100. -200.  300.]
 [ 400.  500. -600.]]
[syft.FloatTensor:20 grad:None size:2x3 c:[] p:[] init:]

In [7]:
b.cumsum(1)

[[-100. -300.    0.]
 [ 400.  900.  300.]]
[syft.FloatTensor:6 grad:None size:2x3 c:[] p:[5] init:view_2_3]

	-----------creators-----------
	[syft.FloatTensor:5 grad:None size:2x3x1 c:[6] p:[4] init:view_2_3_1]
	------------------------------



In [3]:
out = a.view_(2,3)

In [4]:
out

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:1 grad:None size:2x3]

In [5]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:4 grad:None size:2x3]

In [6]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:5 grad:None size:6]

In [7]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

[[-30. -32.  33.]
 [ 34.  35. -36.]]
[syft.FloatTensor:6 grad:None size:2x3]

In [8]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:7 grad:None size:6]

### CPU vs GPU

In [9]:
gpu = True

### Absolute Value

In [10]:
a = FloatTensor(data)

if(gpu):
    a.gpu()

In [11]:
b = a.abs()
b

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor:9 grad:None size:6]

In [ ]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [12]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:8 grad:None size:6]

In [13]:
a.abs_()

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor:8 grad:None size:6]

In [14]:
a.id

8

### Addition

In [15]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [16]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:10 grad:None size:6]

In [17]:
a = a + a
a

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:11 grad:None size:6]

In [18]:
a += a
a

[ -4.  -8.  12.  16.  20. -24.]
[syft.FloatTensor:11 grad:None size:6]

In [19]:
a = a + 3
a

[ -1.  -5.  15.  19.  23. -21.]
[syft.FloatTensor:12 grad:None size:6]

In [20]:
a += 3
a

[  2.  -2.  18.  22.  26. -18.]
[syft.FloatTensor:12 grad:None size:6]

### Subtraction

In [21]:
a = FloatTensor(data)
b = FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

In [22]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:13 grad:None size:6]

In [23]:
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:14 grad:None size:6]

In [24]:
a - b

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor:15 grad:None size:6]

In [25]:
b - a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:16 grad:None size:6]

In [26]:
a - 1

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor:17 grad:None size:6]

In [27]:
b - 2

[ -4.  -6.   4.   6.   8. -14.]
[syft.FloatTensor:18 grad:None size:6]

In [28]:
a -= 1
a

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor:13 grad:None size:6]

In [29]:
b -= 1
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:14 grad:None size:6]

In [30]:
a -= b
a

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor:13 grad:None size:6]

## Multiplication

In [31]:
a = a * a
a

[  1.   4.   9.  16.  25.  36.]
[syft.FloatTensor:19 grad:None size:6]

In [32]:
a *= a
a

[  1.00000000e+00   1.60000000e+01   8.10000000e+01   2.56000000e+02
   6.24999900e+02   1.29600000e+03]
[syft.FloatTensor:19 grad:None size:6]

In [33]:
a = a * 3
a

[  3.00000000e+00   4.80000000e+01   2.43000000e+02   7.68000000e+02
   1.87500000e+03   3.88799900e+03]
[syft.FloatTensor:20 grad:None size:6]

In [34]:
a *= 3
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62499900e+03   1.16640000e+04]
[syft.FloatTensor:20 grad:None size:6]

### Divison

In [35]:
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62499900e+03   1.16640000e+04]
[syft.FloatTensor:20 grad:None size:6]

In [36]:
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:14 grad:None size:6]

In [37]:
a = a/a
a

[  1.00000000e+01   1.45000000e+02   7.30000000e+02   2.30500000e+03
   5.62599900e+03   1.16650000e+04]
[syft.FloatTensor:21 grad:None size:6]

In [38]:
b / a

[-0.3        -0.03448276  0.00684931  0.00303688  0.00159972 -0.00111444]
[syft.FloatTensor:22 grad:None size:6]

In [39]:
a / b

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:23 grad:None size:6]

In [40]:
a / 1

[  1.00000000e+01   1.45000000e+02   7.30000000e+02   2.30500000e+03
   5.62599900e+03   1.16650000e+04]
[syft.FloatTensor:24 grad:None size:6]

In [41]:
b / 1

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:25 grad:None size:6]

In [42]:
a /= b
a

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:21 grad:None size:6]

In [43]:
b /= a
b

[ 0.9         0.1724138   0.03424658  0.02125813  0.01439744  0.01448779]
[syft.FloatTensor:14 grad:None size:6]

In [44]:
a /= a
a

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:21 grad:None size:6]

In [45]:
b /= 1
b

[ 0.9         0.1724138   0.03424658  0.02125813  0.01439744  0.01448779]
[syft.FloatTensor:14 grad:None size:6]

In [46]:
b /= 2
b

[ 0.45        0.0862069   0.01712329  0.01062907  0.00719872  0.00724389]
[syft.FloatTensor:14 grad:None size:6]

In [47]:
a *= 2

In [48]:
a

[   -6.666667   -58.         292.         658.5715    1250.222    -1794.615   ]
[syft.FloatTensor:21 grad:None size:6]