In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor, IntTensor

In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)
b = FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 
d = FloatTensor(np.random.rand(2,6))

In [28]:
x = FloatTensor(list(range(1,25))).view(3,4,2).autograd(True)
y = FloatTensor(list(range(26,50))).view(3,4,2).autograd(True)

xi = IntTensor([1,3,5])

In [29]:
z = syft.concatenate([x,y],axis=0)

In [30]:
z_grad = (z * 1).autograd(False)

In [31]:
z.backward(z_grad)

In [33]:
y.grad()

[[[ 26.  27.]
  [ 28.  29.]
  [ 30.  31.]
  [ 32.  33.]]

 [[ 34.  35.]
  [ 36.  37.]
  [ 38.  39.]
  [ 40.  41.]]

 [[ 42.  43.]
  [ 44.  45.]
  [ 46.  47.]
  [ 48.  49.]]]
[syft.FloatTensor:58 grad:None size:3x4x2 c:[] p:[57] init:view_3_4_2]

	-----------creators-----------
	[syft.FloatTensor:57 grad:None size:1x3x8 c:[58] p:[52] init:index_select_0_11]
	------------------------------



In [14]:
np.concatenate([x.to_numpy(),y.to_numpy()],axis=2)

array([[[  1.,   2.,  26.,  27.],
        [  3.,   4.,  28.,  29.],
        [  5.,   6.,  30.,  31.],
        [  7.,   8.,  32.,  33.]],

       [[  9.,  10.,  34.,  35.],
        [ 11.,  12.,  36.,  37.],
        [ 13.,  14.,  38.,  39.],
        [ 15.,  16.,  40.,  41.]],

       [[ 17.,  18.,  42.,  43.],
        [ 19.,  20.,  44.,  45.],
        [ 21.,  22.,  46.,  47.],
        [ 23.,  24.,  48.,  49.]]])

In [6]:
y

[[ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]
 [ 21.  22.  23.  24.]]
[syft.FloatTensor:8 grad:None size:3x4 c:[9] p:[7] init:view_3_4]

	-----------children-----------
	[syft.FloatTensor:9 grad:None size:1x3x4 c:[] p:[8] init:view_1_3_4]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:7 grad:None size:12 c:[8] p:[] init:]
	------------------------------



In [8]:
xi

[1 3 5]
[syft.IntTensor:1 size:3]

In [12]:
z = syft.controller.concatenate([x,y],axis=0)

In [13]:
z

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]
 [ 21.  22.  23.  24.]]
[syft.FloatTensor:9 grad:None size:6x4 c:[] p:[6, 8] init:concatenate]

	-----------creators-----------
	[syft.FloatTensor:6 grad:None size:3x4 c:[9] p:[5] init:view_3_4]
	[syft.FloatTensor:8 grad:None size:3x4 c:[9] p:[7] init:view_3_4]
	------------------------------



In [4]:
y.save("y.tensor")

'True'

In [5]:
syft.load('y.tensor')

[[ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]
 [ 21.  22.  23.  24.]]
[syft.FloatTensor:9 grad:None size:3x4 c:[] p:[] init:read_from_file]

In [4]:
x.save("x.tensor")

'True'

In [42]:
x

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]
[syft.FloatTensor:1165 grad:None size:3x4 c:[] p:[1164] init:view_3_4]

	-----------creators-----------
	[syft.FloatTensor:1164 grad:None size:12 c:[1165] p:[] init:]
	------------------------------



In [43]:
y

[[ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]
 [ 21.  22.  23.  24.]]
[syft.FloatTensor:1167 grad:None size:3x4 c:[] p:[1166] init:view_3_4]

	-----------creators-----------
	[syft.FloatTensor:1166 grad:None size:12 c:[1167] p:[] init:]
	------------------------------



In [3]:
out = a.view_(2,3)

In [4]:
out

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:1 grad:None size:2x3]

In [5]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:4 grad:None size:2x3]

In [6]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:5 grad:None size:6]

In [7]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

[[-30. -32.  33.]
 [ 34.  35. -36.]]
[syft.FloatTensor:6 grad:None size:2x3]

In [8]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:7 grad:None size:6]

### CPU vs GPU

In [9]:
gpu = True

### Absolute Value

In [10]:
a = FloatTensor(data)

if(gpu):
    a.gpu()

In [11]:
b = a.abs()
b

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor:9 grad:None size:6]

In [ ]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [12]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:8 grad:None size:6]

In [13]:
a.abs_()

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor:8 grad:None size:6]

In [14]:
a.id

8

### Addition

In [15]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [16]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:10 grad:None size:6]

In [17]:
a = a + a
a

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:11 grad:None size:6]

In [18]:
a += a
a

[ -4.  -8.  12.  16.  20. -24.]
[syft.FloatTensor:11 grad:None size:6]

In [19]:
a = a + 3
a

[ -1.  -5.  15.  19.  23. -21.]
[syft.FloatTensor:12 grad:None size:6]

In [20]:
a += 3
a

[  2.  -2.  18.  22.  26. -18.]
[syft.FloatTensor:12 grad:None size:6]

### Subtraction

In [21]:
a = FloatTensor(data)
b = FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

In [22]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:13 grad:None size:6]

In [23]:
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:14 grad:None size:6]

In [24]:
a - b

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor:15 grad:None size:6]

In [25]:
b - a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:16 grad:None size:6]

In [26]:
a - 1

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor:17 grad:None size:6]

In [27]:
b - 2

[ -4.  -6.   4.   6.   8. -14.]
[syft.FloatTensor:18 grad:None size:6]

In [28]:
a -= 1
a

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor:13 grad:None size:6]

In [29]:
b -= 1
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:14 grad:None size:6]

In [30]:
a -= b
a

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor:13 grad:None size:6]

## Multiplication

In [31]:
a = a * a
a

[  1.   4.   9.  16.  25.  36.]
[syft.FloatTensor:19 grad:None size:6]

In [32]:
a *= a
a

[  1.00000000e+00   1.60000000e+01   8.10000000e+01   2.56000000e+02
   6.24999900e+02   1.29600000e+03]
[syft.FloatTensor:19 grad:None size:6]

In [33]:
a = a * 3
a

[  3.00000000e+00   4.80000000e+01   2.43000000e+02   7.68000000e+02
   1.87500000e+03   3.88799900e+03]
[syft.FloatTensor:20 grad:None size:6]

In [34]:
a *= 3
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62499900e+03   1.16640000e+04]
[syft.FloatTensor:20 grad:None size:6]

### Divison

In [35]:
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62499900e+03   1.16640000e+04]
[syft.FloatTensor:20 grad:None size:6]

In [36]:
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:14 grad:None size:6]

In [37]:
a = a/a
a

[  1.00000000e+01   1.45000000e+02   7.30000000e+02   2.30500000e+03
   5.62599900e+03   1.16650000e+04]
[syft.FloatTensor:21 grad:None size:6]

In [38]:
b / a

[-0.3        -0.03448276  0.00684931  0.00303688  0.00159972 -0.00111444]
[syft.FloatTensor:22 grad:None size:6]

In [39]:
a / b

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:23 grad:None size:6]

In [40]:
a / 1

[  1.00000000e+01   1.45000000e+02   7.30000000e+02   2.30500000e+03
   5.62599900e+03   1.16650000e+04]
[syft.FloatTensor:24 grad:None size:6]

In [41]:
b / 1

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor:25 grad:None size:6]

In [42]:
a /= b
a

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:21 grad:None size:6]

In [43]:
b /= a
b

[ 0.9         0.1724138   0.03424658  0.02125813  0.01439744  0.01448779]
[syft.FloatTensor:14 grad:None size:6]

In [44]:
a /= a
a

[  -3.333333  -29.        146.        329.2857    625.111    -897.3075  ]
[syft.FloatTensor:21 grad:None size:6]

In [45]:
b /= 1
b

[ 0.9         0.1724138   0.03424658  0.02125813  0.01439744  0.01448779]
[syft.FloatTensor:14 grad:None size:6]

In [46]:
b /= 2
b

[ 0.45        0.0862069   0.01712329  0.01062907  0.00719872  0.00724389]
[syft.FloatTensor:14 grad:None size:6]

In [47]:
a *= 2

In [6]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:1131 grad:None size:6 c:[] p:[] init:]