In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor, IntTensor

/home/jason/anaconda3/envs/openmined/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)
b = FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 
d = FloatTensor(np.random.rand(2,6))

In [3]:
x = FloatTensor(list(range(1,25))).view(3,4,2).autograd(True)
y = FloatTensor(list(range(26,50))).view(3,4,2).autograd(True)

xi = IntTensor([1,3,5])

In [4]:
z = syft.concatenate([x,y],axis=0)

In [5]:
z_grad = (z * 1).autograd(False)

In [6]:
z.backward(z_grad)

In [7]:
y.grad()

[[[26. 27.]
  [28. 29.]
  [30. 31.]
  [32. 33.]]

 [[34. 35.]
  [36. 37.]
  [38. 39.]
  [40. 41.]]

 [[42. 43.]
  [44. 45.]
  [46. 47.]
  [48. 49.]]]
[syft.FloatTensor:16 grad:None size:3x4x2 c:[] p:[15] init:view_3_4_2]

	-----------creators-----------
	[syft.FloatTensor:15 grad:None size:1x3x8 c:[16] p:[10] init:index_select_0_3]
	------------------------------



In [8]:
np.concatenate([x.to_numpy(),y.to_numpy()],axis=2)

array([[[ 1.,  2., 26., 27.],
        [ 3.,  4., 28., 29.],
        [ 5.,  6., 30., 31.],
        [ 7.,  8., 32., 33.]],

       [[ 9., 10., 34., 35.],
        [11., 12., 36., 37.],
        [13., 14., 38., 39.],
        [15., 16., 40., 41.]],

       [[17., 18., 42., 43.],
        [19., 20., 44., 45.],
        [21., 22., 46., 47.],
        [23., 24., 48., 49.]]])

In [9]:
y

[[[26. 27.]
  [28. 29.]
  [30. 31.]
  [32. 33.]]

 [[34. 35.]
  [36. 37.]
  [38. 39.]
  [40. 41.]]

 [[42. 43.]
  [44. 45.]
  [46. 47.]
  [48. 49.]]]
[syft.FloatTensor:8 grad:16 size:3x4x2 c:[9] p:[] init:view_3_4_2]

	-----------children-----------
	[syft.FloatTensor:9 grad:10 size:6x4x2 c:[10] p:[6, 8] init:concatenate_0]
	------------------------------



In [10]:
xi

[1 3 5]
[syft.IntTensor:1 size:3]

In [11]:
y.save("y.tensor")

'True'

In [12]:
syft.load('y.tensor')

[[[26. 27.]
  [28. 29.]
  [30. 31.]
  [32. 33.]]

 [[34. 35.]
  [36. 37.]
  [38. 39.]
  [40. 41.]]

 [[42. 43.]
  [44. 45.]
  [46. 47.]
  [48. 49.]]]
[syft.FloatTensor:17 grad:None size:3x4x2 c:[] p:[] init:read_from_file]

In [13]:
x.save("x.tensor")

'True'

In [14]:
x

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]
  [13. 14.]
  [15. 16.]]

 [[17. 18.]
  [19. 20.]
  [21. 22.]
  [23. 24.]]]
[syft.FloatTensor:6 grad:14 size:3x4x2 c:[9] p:[] init:view_3_4_2]

	-----------children-----------
	[syft.FloatTensor:9 grad:10 size:6x4x2 c:[10] p:[6, 8] init:concatenate_0]
	------------------------------



In [15]:
y

[[[26. 27.]
  [28. 29.]
  [30. 31.]
  [32. 33.]]

 [[34. 35.]
  [36. 37.]
  [38. 39.]
  [40. 41.]]

 [[42. 43.]
  [44. 45.]
  [46. 47.]
  [48. 49.]]]
[syft.FloatTensor:8 grad:16 size:3x4x2 c:[9] p:[] init:view_3_4_2]

	-----------children-----------
	[syft.FloatTensor:9 grad:10 size:6x4x2 c:[10] p:[6, 8] init:concatenate_0]
	------------------------------



In [16]:
out = a.view_(2,3)

In [17]:
out

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:1 grad:None size:2x3 c:[] p:[] init:]

In [18]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor:18 grad:None size:2x3 c:[] p:[1] init:view_2_3]

	-----------creators-----------
	[syft.FloatTensor:1 grad:None size:2x3 c:[18] p:[] init:]
	------------------------------



In [19]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:19 grad:None size:6 c:[] p:[2] init:view_6]

	-----------creators-----------
	[syft.FloatTensor:2 grad:None size:2x3 c:[19] p:[] init:]
	------------------------------



In [20]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

[[-30. -32.  33.]
 [ 34.  35. -36.]]
[syft.FloatTensor:20 grad:None size:2x3 c:[] p:[3] init:view_2_3]

	-----------creators-----------
	[syft.FloatTensor:3 grad:None size:6 c:[20] p:[] init:]
	------------------------------



In [21]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor:19 grad:None size:6 c:[] p:[2] init:view_6]

	-----------creators-----------
	[syft.FloatTensor:2 grad:None size:2x3 c:[19] p:[] init:]
	------------------------------



### CPU vs GPU

In [22]:
gpu = True

### Absolute Value

In [23]:
a = FloatTensor(data)

if(gpu):
    a.gpu()

In [24]:
b = a.abs()
b

[1. 2. 3. 4. 5. 6.]
[syft.FloatTensor:22 grad:None size:6 c:[] p:[21] init:abs]

	-----------creators-----------
	[syft.FloatTensor:21 grad:None size:6 c:[22] p:[] init:]
	------------------------------



In [25]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [26]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:23 grad:None size:6 c:[] p:[] init:]

In [27]:
a.abs_()

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:23 grad:None size:6 c:[] p:[] init:]

In [28]:
a.id

23

### Addition

In [29]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [30]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:24 grad:None size:6 c:[] p:[] init:]

In [31]:
a = a + a
a

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:25 grad:None size:6 c:[] p:[24, 24] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:24 grad:None size:6 c:[25, 25] p:[] init:]
	[syft.FloatTensor:24 grad:None size:6 c:[25, 25] p:[] init:]
	------------------------------



In [32]:
a += a
a

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:25 grad:None size:6 c:[] p:[24, 24] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:24 grad:None size:6 c:[25, 25] p:[] init:]
	[syft.FloatTensor:24 grad:None size:6 c:[25, 25] p:[] init:]
	------------------------------



In [33]:
a = a + 3
a

[ 1. -1.  9. 11. 13. -9.]
[syft.FloatTensor:26 grad:None size:6 c:[] p:[25, 27] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:25 grad:None size:6 c:[26] p:[24, 24] init:add_elem]
	[syft.FloatTensor:27 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



In [34]:
a += 3
a

[ 1. -1.  9. 11. 13. -9.]
[syft.FloatTensor:26 grad:None size:6 c:[] p:[25, 27] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:25 grad:None size:6 c:[26] p:[24, 24] init:add_elem]
	[syft.FloatTensor:27 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



### Subtraction

In [35]:
a = FloatTensor(data)
b = FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

In [36]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:28 grad:None size:6 c:[] p:[] init:]

In [37]:
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[] p:[] init:]

In [38]:
a - b

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]

	-----------creators-----------
	[syft.FloatTensor:28 grad:None size:6 c:[30] p:[] init:]
	[syft.FloatTensor:29 grad:None size:6 c:[30] p:[] init:]
	------------------------------



In [39]:
b - a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]

	-----------creators-----------
	[syft.FloatTensor:28 grad:None size:6 c:[30] p:[] init:]
	[syft.FloatTensor:29 grad:None size:6 c:[30] p:[] init:]
	------------------------------



In [40]:
a - 1

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor:31 grad:None size:6 c:[] p:[28, 32] init:sub_scalar]

	-----------creators-----------
	[syft.FloatTensor:28 grad:None size:6 c:[30, 31] p:[] init:]
	[syft.FloatTensor:32 grad:None size:1 c:[] p:[] init:sub_scalar]
	------------------------------



In [41]:
b - 2

[ -4.  -6.   4.   6.   8. -14.]
[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]

	-----------creators-----------
	[syft.FloatTensor:29 grad:None size:6 c:[30, 33] p:[] init:]
	[syft.FloatTensor:34 grad:None size:1 c:[] p:[] init:sub_scalar]
	------------------------------



In [42]:
a -= 1
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:28 grad:None size:6 c:[30, 31] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:31 grad:None size:6 c:[] p:[28, 32] init:sub_scalar]
	------------------------------



In [43]:
b -= 1
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[30, 33] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]
	------------------------------



In [44]:
a -= b
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor:28 grad:None size:6 c:[30, 31] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:31 grad:None size:6 c:[] p:[28, 32] init:sub_scalar]
	------------------------------



## Multiplication

In [45]:
a = a * a
a

[ 1.  4.  9. 16. 25. 36.]
[syft.FloatTensor:35 grad:None size:6 c:[] p:[28, 28] init:mul_elem]

	-----------creators-----------
	[syft.FloatTensor:28 grad:None size:6 c:[30, 31, 35, 35] p:[] init:]
	[syft.FloatTensor:28 grad:None size:6 c:[30, 31, 35, 35] p:[] init:]
	------------------------------



In [46]:
a *= a
a

[ 1.  4.  9. 16. 25. 36.]
[syft.FloatTensor:35 grad:None size:6 c:[] p:[28, 28] init:mul_elem]

	-----------creators-----------
	[syft.FloatTensor:28 grad:None size:6 c:[30, 31, 35, 35] p:[] init:]
	[syft.FloatTensor:28 grad:None size:6 c:[30, 31, 35, 35] p:[] init:]
	------------------------------



In [47]:
a = a * 3
a

[  3.       12.       27.       48.       74.99999 108.     ]
[syft.FloatTensor:36 grad:None size:6 c:[] p:[35, 37] init:mul_scalar]

	-----------creators-----------
	[syft.FloatTensor:35 grad:None size:6 c:[36] p:[28, 28] init:mul_elem]
	[syft.FloatTensor:37 grad:None size:1 c:[] p:[] init:mul_scalar]
	------------------------------



In [48]:
a *= 3
a

[  3.       12.       27.       48.       74.99999 108.     ]
[syft.FloatTensor:36 grad:None size:6 c:[] p:[35, 37] init:mul_scalar]

	-----------creators-----------
	[syft.FloatTensor:35 grad:None size:6 c:[36] p:[28, 28] init:mul_elem]
	[syft.FloatTensor:37 grad:None size:1 c:[] p:[] init:mul_scalar]
	------------------------------



### Divison

In [49]:
a

[  3.       12.       27.       48.       74.99999 108.     ]
[syft.FloatTensor:36 grad:None size:6 c:[] p:[35, 37] init:mul_scalar]

	-----------creators-----------
	[syft.FloatTensor:35 grad:None size:6 c:[36] p:[28, 28] init:mul_elem]
	[syft.FloatTensor:37 grad:None size:1 c:[] p:[] init:mul_scalar]
	------------------------------



In [50]:
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[30, 33] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]
	------------------------------



In [51]:
a = a/a
a

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:38 grad:None size:6 c:[] p:[36, 36] init:div_elem]

	-----------creators-----------
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	------------------------------



In [52]:
b / a

[-inf -inf  inf  inf  inf -inf]
[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]

	-----------creators-----------
	[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39] p:[] init:]
	[syft.FloatTensor:38 grad:None size:6 c:[39] p:[36, 36] init:div_elem]
	------------------------------



In [53]:
a / b

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]

	-----------creators-----------
	[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39] p:[] init:]
	[syft.FloatTensor:38 grad:None size:6 c:[39] p:[36, 36] init:div_elem]
	------------------------------



In [54]:
a / 1

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:40 grad:None size:6 c:[] p:[38, 41] init:div_scalar]

	-----------creators-----------
	[syft.FloatTensor:38 grad:None size:6 c:[39, 40] p:[36, 36] init:div_elem]
	[syft.FloatTensor:41 grad:None size:1 c:[] p:[] init:div_scalar]
	------------------------------



In [55]:
b / 1

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:42 grad:None size:6 c:[] p:[29, 43] init:div_scalar]

	-----------creators-----------
	[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39, 42] p:[] init:]
	[syft.FloatTensor:43 grad:None size:1 c:[] p:[] init:div_scalar]
	------------------------------



In [56]:
a /= b
a

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:38 grad:None size:6 c:[39, 40] p:[36, 36] init:div_elem]

	-----------children-----------
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:40 grad:None size:6 c:[] p:[38, 41] init:div_scalar]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	------------------------------



In [57]:
b /= a
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39, 42] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:42 grad:None size:6 c:[] p:[29, 43] init:div_scalar]
	------------------------------



In [58]:
a /= a
a

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:38 grad:None size:6 c:[39, 40] p:[36, 36] init:div_elem]

	-----------children-----------
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:40 grad:None size:6 c:[] p:[38, 41] init:div_scalar]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	------------------------------



In [59]:
b /= 1
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39, 42] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:42 grad:None size:6 c:[] p:[29, 43] init:div_scalar]
	------------------------------



In [60]:
b /= 2
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor:29 grad:None size:6 c:[30, 33, 39, 42] p:[] init:]

	-----------children-----------
	[syft.FloatTensor:30 grad:None size:6 c:[] p:[28, 29] init:sub_elem]
	[syft.FloatTensor:33 grad:None size:6 c:[] p:[29, 34] init:sub_scalar]
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:42 grad:None size:6 c:[] p:[29, 43] init:div_scalar]
	------------------------------



In [61]:
a *= 2

In [62]:
a

[0. 0. 0. 0. 0. 0.]
[syft.FloatTensor:38 grad:None size:6 c:[39, 40] p:[36, 36] init:div_elem]

	-----------children-----------
	[syft.FloatTensor:39 grad:None size:6 c:[] p:[29, 38] init:div_elem]
	[syft.FloatTensor:40 grad:None size:6 c:[] p:[38, 41] init:div_scalar]
	------------------------------

	-----------creators-----------
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	[syft.FloatTensor:36 grad:None size:6 c:[38, 38] p:[35, 37] init:mul_scalar]
	------------------------------

