In [1]:
import syft.syft as syft
import imp
imp.reload(syft)
from syft.syft import FloatTensor, SyftController
import numpy as np

# connect -- rerun this block if you make changes to the unity back-end
#         -- the controller is not yet smart enough to retry connection
#         -- on its own
sc = SyftController(verbose=False)

In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = sc.FloatTensor(data)
b = sc.FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = sc.FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 

In [3]:
out = a.view_(2,3)

In [4]:
out

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor of size 2x3]

In [5]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor of size 2x3]

In [6]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor of size 6]

In [7]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

[[-30. -32.  33.]
 [ 34.  35. -36.]]
[syft.FloatTensor of size 2x3]

In [8]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor of size 6]

### CPU vs GPU

In [9]:
gpu = False

### Absolute Value

In [10]:
a = sc.FloatTensor(data)

if(gpu):
    a.gpu()

In [11]:
b = a.abs()
b

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor of size 6]

In [12]:
a = sc.FloatTensor(data)
if(gpu):
    a.gpu()

In [13]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor of size 6]

In [14]:
a.abs_()

[ 1.  2.  3.  4.  5.  6.]
[syft.FloatTensor of size 6]

In [15]:
a.id

22

### Addition

In [16]:
a = sc.FloatTensor(data)
if(gpu):
    a.gpu()

In [17]:
a = a + a
a

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor of size 6]

In [18]:
a += a
a

[ -4.  -8.  12.  16.  20. -24.]
[syft.FloatTensor of size 6]

In [19]:
a = a + 3
a

[ -1.  -5.  15.  19.  23. -21.]
[syft.FloatTensor of size 6]

In [20]:
a += 3
a

[  2.  -2.  18.  22.  26. -18.]
[syft.FloatTensor of size 6]

### Subtraction

In [21]:
a = sc.FloatTensor(data)
b = sc.FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

In [22]:
a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor of size 6]

In [23]:
b

[ -2.  -4.   6.   8.  10. -12.]
[syft.FloatTensor of size 6]

In [24]:
a - b

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor of size 6]

In [25]:
b - a

[-1. -2.  3.  4.  5. -6.]
[syft.FloatTensor of size 6]

In [26]:
a - 1

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor of size 6]

In [27]:
b - 2

[ -4.  -6.   4.   6.   8. -14.]
[syft.FloatTensor of size 6]

In [28]:
a -= 1
a

[-2. -3.  2.  3.  4. -7.]
[syft.FloatTensor of size 6]

In [29]:
b -= 1
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor of size 6]

In [30]:
a -= b
a

[ 1.  2. -3. -4. -5.  6.]
[syft.FloatTensor of size 6]

## Multiplication

In [31]:
a = a * a
a

[  1.   4.   9.  16.  25.  36.]
[syft.FloatTensor of size 6]

In [32]:
a *= a
a

[  1.00000000e+00   1.60000000e+01   8.10000000e+01   2.56000000e+02
   6.25000000e+02   1.29600000e+03]
[syft.FloatTensor of size 6]

In [33]:
a = a * 3
a

[  3.00000000e+00   4.80000000e+01   2.43000000e+02   7.68000000e+02
   1.87500000e+03   3.88800000e+03]
[syft.FloatTensor of size 6]

In [34]:
a *= 3
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62500000e+03   1.16640000e+04]
[syft.FloatTensor of size 6]

### Divison

In [35]:
a

[  9.00000000e+00   1.44000000e+02   7.29000000e+02   2.30400000e+03
   5.62500000e+03   1.16640000e+04]
[syft.FloatTensor of size 6]

In [36]:
b

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor of size 6]

In [37]:
a = a/a
a

[ 1.  1.  1.  1.  1.  1.]
[syft.FloatTensor of size 6]

In [38]:
b / a

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor of size 6]

In [39]:
a / b

[-0.3333333  -0.2         0.2         0.1428571   0.1111111  -0.07692308]
[syft.FloatTensor of size 6]

In [40]:
a / 1

[ 1.  1.  1.  1.  1.  1.]
[syft.FloatTensor of size 6]

In [41]:
b / 1

[ -3.  -5.   5.   7.   9. -13.]
[syft.FloatTensor of size 6]

In [42]:
a /= b
a

[-0.3333333  -0.2         0.2         0.1428571   0.1111111  -0.07692308]
[syft.FloatTensor of size 6]

In [43]:
b /= a
b

[   9.   25.   25.   49.   81.  169.]
[syft.FloatTensor of size 6]

In [44]:
a /= a
a

[ 1.  1.  1.  1.  1.  1.]
[syft.FloatTensor of size 6]

In [45]:
b /= 1
b

[   9.   25.   25.   49.   81.  169.]
[syft.FloatTensor of size 6]

In [46]:
b /= 2
b

[  4.5  12.5  12.5  24.5  40.5  84.5]
[syft.FloatTensor of size 6]

In [47]:
a *= 2

In [48]:
a

[ 2.  2.  2.  2.  2.  2.]
[syft.FloatTensor of size 6]

In [49]:
a

[ 2.  2.  2.  2.  2.  2.]
[syft.FloatTensor of size 6]

In [50]:
a **= 3

In [51]:
a

[ 8.  8.  8.  8.  8.  8.]
[syft.FloatTensor of size 6]

In [52]:
a = a**2
a

[ 64.  64.  64.  64.  64.  64.]
[syft.FloatTensor of size 6]