This is not a robust testing suite, but simply verifies which functions have been implemented and are working.

I use this notebook to generate the expected values when adding to `integration/tests.py`. 

Following [Torch math operations](http://pytorch.org/docs/master/torch.html#math-operations).

Completed abs() through fmod(), feel free to continue building tests! 

Skipped:

- add()
- atan2(input1, input2, out=None)
- div()

Remaining:

- The three above
- Everything below fmod() in the link provided above

Want to pick up where I left off? Start [here](http://pytorch.org/docs/master/torch.html#torch.frac).

In general, I'll build both a PySyft tensor and a PyTorch tensor, perform the same operation and ensure the result is the same.

In [1]:
import syft
import syft.nn as nn
import syft.controller
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor

In [2]:
import torch

## Comparing PySyft operations to PyTorch operations

#### abs()

In [3]:
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

In [ ]:
a.abs()

In [ ]:
b.abs()

In [ ]:
np.testing.assert_almost_equal(a.abs().to_numpy(), b.abs().numpy(), decimal=4)

#### acos()

In [ ]:
data = np.array([-0.6366, 0.2718, 0.4469, 1.3122]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

In [ ]:
a.acos().to_numpy()

In [ ]:
b.acos().numpy()

In [ ]:
np.testing.assert_almost_equal(a.acos().to_numpy(), b.acos().numpy(), decimal=4)

#### add()

#### addcdiv()

In [63]:
t = torch.randn(2, 3)
t1 = torch.randn(1, 6)
t2 = torch.randn(6, 1)

In [64]:
t.numpy()

array([[-0.39069918,  0.18299954,  0.31636572],
       [ 1.13772225, -0.3253836 , -0.88367993]], dtype=float32)

In [65]:
t1.numpy()

array([[-0.59233409,  0.05522861, -2.57116127,  1.35875595, -0.87830114,
         0.53922689]], dtype=float32)

In [66]:
t2.numpy()

array([[ 0.30240816],
       [ 0.48581797],
       [-0.61623448],
       [-1.08655083],
       [-0.45116752],
       [-0.72556847]], dtype=float32)

In [71]:
data = np.array([[-0.39069918,  0.18299954,  0.31636572],
                 [ 1.13772225, -0.3253836 , -0.88367993]]).astype('float')
t1 = np.array([[-0.59233409,  0.05522861, -2.57116127,  
                1.35875595, -0.87830114, 0.53922689]]).astype('float')
t2 = np.array([[ 0.30240816], [ 0.48581797], [-0.61623448], 
               [-1.08655083], [-0.45116752], [-0.72556847]]).astype('float')

a = FloatTensor(data)
numerator_a = FloatTensor(t1)
denominator_a = FloatTensor(t2)

b = torch.FloatTensor(data)
numerator_b = torch.FloatTensor(t1)
denominator_b = torch.FloatTensor(t2)

value = 0.1

FloatTensor.__init__: 471
SyftController.processMessage: Command not found.
FloatTensor.__init__: 472
FloatTensor.__init__: 473


In [ ]:
a.addcdiv(value, numerator_a, denominator_a).to_numpy()

In [74]:
b.addcdiv(value, numerator_b, denominator_b).numpy()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: self, tensor1, and tensor2 not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  """Entry point for launching an IPython kernel.


array([[-0.58657157,  0.19436771,  0.73360324],
       [ 1.01267004, -0.13071065, -0.9579978 ]], dtype=float32)

In [75]:
np.testing.assert_almost_equal(a.addcdiv(value, numerator_a, denominator_a).to_numpy(), 
                               b.addcdiv(value, numerator_b, denominator_b).numpy(), decimal=4)

AttributeError: 'FloatTensor' object has no attribute 'addcdiv'

#### addcmul()

In [4]:
data = np.array([[-0.39069918,  0.18299954,  0.31636572],
                 [ 1.13772225, -0.3253836 , -0.88367993]]).astype('float')
t1 = np.array([[-0.59233409,  0.05522861, -2.57116127,  
                1.35875595, -0.87830114, 0.53922689]]).astype('float')
t2 = np.array([[ 0.30240816], [ 0.48581797], [-0.61623448], 
               [-1.08655083], [-0.45116752], [-0.72556847]]).astype('float')

a = FloatTensor(data)
t1_a = FloatTensor(t1)
t2_a = FloatTensor(t2)

b = torch.FloatTensor(data)
t1_b = torch.FloatTensor(t1)
t2_b = torch.FloatTensor(t2)

value = 0.1

In [ ]:
a.addcmul(value, t1_a, t2_a).to_numpy()

In [78]:
b.addcmul(value, t1_b, t2_b).numpy()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: self, tensor1, and tensor2 not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  """Entry point for launching an IPython kernel.


array([[-0.40861183,  0.18568264,  0.47480953],
       [ 0.9900865 , -0.28575751, -0.92280453]], dtype=float32)

In [ ]:
np.testing.assert_almost_equal(a.addcmul(value, t1_a, t2_a).to_numpy(), 
                               b.addcmul(value, t1_b, t2_b).numpy(), decimal=4)

In [ ]:
np.array([[-0.40861183,  0.18568264,  0.47480953],
          [ 0.9900865 , -0.28575751, -0.92280453]]).astype('float')

#### asin()

In [3]:
data = np.array([-0.6366, 0.2718, 0.4469, 1.3122]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 189


In [4]:
a.asin().to_numpy()

190
FloatTensor.__init__: 190


array([-0.6900815,  0.275263 ,  0.463297 ,        nan])

In [5]:
b.asin().numpy()

array([-0.69008148,  0.27526295,  0.46329704,         nan], dtype=float32)

In [6]:
np.testing.assert_almost_equal(a.asin().to_numpy(), b.asin().numpy(), decimal=4)

192
FloatTensor.__init__: 192


#### atan()

In [7]:
data = np.array([-0.6366, 0.2718, 0.4469, 1.3122]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 215
SyftController.processMessage: Command not found.


In [9]:
a.atan().to_numpy()

218
FloatTensor.__init__: 218


array([-0.5668975,  0.2653888,  0.420273 ,  0.9196094])

In [10]:
b.atan().numpy()

array([-0.56689745,  0.26538879,  0.42027298,  0.91960937], dtype=float32)

In [11]:
np.testing.assert_almost_equal(a.atan().to_numpy(), b.atan().numpy(), decimal=4)

220
FloatTensor.__init__: 220


#### atan2()

#### ceil()

In [12]:
data = np.array([1.3869, 0.3912, -0.8634, -0.5468]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 249


In [13]:
a.ceil().to_numpy()

250
FloatTensor.__init__: 250


array([ 2.,  1.,  0.,  0.])

In [14]:
b.ceil().numpy()

array([ 2.,  1., -0., -0.], dtype=float32)

In [15]:
np.testing.assert_almost_equal(a.ceil().to_numpy(), b.ceil().numpy(), decimal=4)

252
FloatTensor.__init__: 252


#### clamp()

In [79]:
data = np.array([1.3869, 0.3912, -0.8634, -0.5468]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 477
SyftController.processMessage: Command not found.


In [ ]:
a.clamp(min=-0.5, max=0.5).to_numpy()

In [80]:
b.clamp(min=-0.5, max=0.5).numpy()

array([ 0.5       ,  0.39120001, -0.5       , -0.5       ], dtype=float32)

In [ ]:
np.testing.assert_almost_equal(a.clamp(min=-0.5, max=0.5).to_numpy(), b.clamp(min=-0.5, max=0.5).numpy(), decimal=4)

#### cos()

In [26]:
data = np.array([-0.6366, 0.2718, 0.4469, 1.3122]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 295
SyftController.processMessage: Command not found.


In [23]:
a.cos().to_numpy()

292
FloatTensor.__init__: 292


array([ 0.8041216,  0.9632892,  0.9017912,  0.2557239])

In [24]:
b.cos().numpy()

array([ 0.80412155,  0.9632892 ,  0.90179116,  0.25572386], dtype=float32)

In [27]:
np.testing.assert_almost_equal(a.cos().to_numpy(), b.cos().numpy(), decimal=4)

295
FloatTensor.__init__: 295


#### cosh()

In [5]:
data = np.array([-0.6366, 0.2718, 0.4469, 1.3122]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

In [6]:
a.cosh().to_numpy()

array([ 1.209566,  1.037166,  1.101533,  1.991782])

In [33]:
b.cosh().numpy()

array([ 1.209566  ,  1.03716552,  1.10153294,  1.99178159], dtype=float32)

In [31]:
np.testing.assert_almost_equal(a.cosh().to_numpy(), b.cosh().numpy(), decimal=4)

300
FloatTensor.__init__: 300


#### erf()

In [34]:
data = np.array([0, -1., 10.]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 347
SyftController.processMessage: Command not found.


In [38]:
a.erf().to_numpy()

AttributeError: 'FloatTensor' object has no attribute 'erf'

In [39]:
b.erf().numpy()

array([ 0.        , -0.84270078,  1.        ], dtype=float32)

In [37]:
np.testing.assert_almost_equal(a.erf().to_numpy(), b.erf().numpy(), decimal=4)

AttributeError: 'FloatTensor' object has no attribute 'erf'

#### erfinv()

In [41]:
data = np.array([0, 0.5, -1.]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 395
SyftController.processMessage: Command not found.


In [44]:
a.erfinv.to_numpy()

AttributeError: 'FloatTensor' object has no attribute 'erfinv'

In [42]:
b.erfinv().numpy()

array([ 0.        ,  0.47693628,        -inf], dtype=float32)

In [45]:
np.testing.assert_almost_equal(a.erfinv().to_numpy(), b.erfinv().numpy(), decimal=4)

AttributeError: 'FloatTensor' object has no attribute 'erfinv'

#### exp()

In [48]:
data = np.array([0, np.log(2)]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 396
SyftController.processMessage: Command not found.


In [49]:
a.exp().to_numpy()

397
FloatTensor.__init__: 397


array([ 1.,  2.])

In [50]:
b.exp().numpy()

array([ 1.,  2.], dtype=float32)

In [51]:
np.testing.assert_almost_equal(a.exp().to_numpy(), b.exp().numpy(), decimal=4)

399
FloatTensor.__init__: 399


#### floor()

In [52]:
data = np.array([1.3869, 0.3912, -0.8634, -0.5468]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 401
SyftController.processMessage: Command not found.


In [53]:
a.floor().to_numpy()

402
FloatTensor.__init__: 402


array([ 1.,  0., -1., -1.])

In [54]:
b.floor().numpy()

array([ 1.,  0., -1., -1.], dtype=float32)

In [55]:
np.testing.assert_almost_equal(a.floor().to_numpy(), b.floor().numpy(), decimal=4)

404
FloatTensor.__init__: 404


#### fmod()

In [58]:
data = np.array([-3, -2, -1, 1, 2, 3]).astype('float')
a = FloatTensor(data)
b = torch.FloatTensor(data)

FloatTensor.__init__: 438
SyftController.processMessage: Command not found.


In [ ]:
a.fmod(2).to_numpy()

In [59]:
b.fmod(2).numpy()

array([-1., -0., -1.,  1.,  0.,  1.], dtype=float32)

In [ ]:
np.testing.assert_almost_equal(a.fmod(2).to_numpy(), b.fmod(2).numpy(), decimal=4)