In [1]:
import syft.syft as syft
import imp
imp.reload(syft)
from syft.syft import FloatTensor, SyftController
import numpy as np

# connect -- rerun this block if you make changes to the unity back-end
#         -- the controller is not yet smart enough to retry connection
#         -- on its own
sc = SyftController()

In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = sc.FloatTensor(data)
b = sc.FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = sc.FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 

FloatTensor.__init__: 129
FloatTensor.__init__: 130
FloatTensor.__init__: 131


In [3]:
a.view_(2,3)

129
132
FloatTensor.__init__: 132
133
FloatTensor.__init__: 133


[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor of size 2x3]

In [4]:
a

134
FloatTensor.__init__: 134
135
FloatTensor.__init__: 135


[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor of size 2x3]

In [5]:
b

136
FloatTensor.__init__: 136
137
FloatTensor.__init__: 137


[[-100. -200.  300.]
 [ 400.  500. -600.]]
[syft.FloatTensor of size 2x3]

In [6]:
c

138
FloatTensor.__init__: 138
139
FloatTensor.__init__: 139


[-30. -32.  33.  34.  35. -36.]
[syft.FloatTensor of size 6]

In [7]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

140
FloatTensor.__init__: 140


[[-1. -2.  3.]
 [ 4.  5. -6.]]
[syft.FloatTensor of size 2x3]

In [8]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

143
FloatTensor.__init__: 143


[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor of size 6]

In [9]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

146
FloatTensor.__init__: 146


[[-30. -32.  33.]
 [ 34.  35. -36.]]
[syft.FloatTensor of size 2x3]

In [10]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

149
FloatTensor.__init__: 149


[-100. -200.  300.  400.  500. -600.]
[syft.FloatTensor of size 6]

### CPU vs GPU

In [4]:
gpu = True

### Absolute Value

In [5]:
a = sc.FloatTensor(data)

if(gpu):
    a.gpu()

FloatTensor.__init__: 1
gpu: OK : Moved data to GPU.


In [6]:
b = a.abs()
b

2
FloatTensor.__init__: 2


1,	2,	3,	4,	5,	6,	


In [7]:
a = sc.FloatTensor(data)
if(gpu):
    a.gpu()

FloatTensor.__init__: 3
SyftController.processMessage: Command not found.
gpu: OK : Moved data to GPU.


In [8]:
a

-1,	-2,	3,	4,	5,	-6,	




-1,	-2,	3,	4,	5,	-6,	


In [8]:
a.abs_()

3
1,	2,	3,	4,	5,	6,	


4
1,	2,	3,	4,	5,	6,	




1,	2,	3,	4,	5,	6,	


In [10]:
a.id

3

### Addition

In [11]:
a = sc.FloatTensor(data)
if(gpu):
    a.gpu()

FloatTensor.__init__: 4
gpu: OK : Moved data to GPU.


In [12]:
a = a + a
a

SyftController.processMessage: Command not found.


-2,	-4,	6,	8,	10,	-12,	


In [13]:
a += a
a

-4,	-8,	12,	16,	20,	-24,	


In [14]:
a = a + 3
a

-1,	-5,	15,	19,	23,	-21,	


In [15]:
a += 3
a

2,	-2,	18,	22,	26,	-18,	


### Subtraction

In [16]:
a = sc.FloatTensor(data)
b = sc.FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

FloatTensor.__init__: 7
FloatTensor.__init__: 8
gpu: OK : Moved data to GPU.
gpu: OK : Moved data to GPU.


In [17]:
a

-1,	-2,	3,	4,	5,	-6,	




-1,	-2,	3,	4,	5,	-6,	


In [18]:
b

-2,	-4,	6,	8,	10,	-12,	




-2,	-4,	6,	8,	10,	-12,	


In [19]:
a - b

1,	2,	-3,	-4,	-5,	6,	


In [20]:
b - a

-1,	-2,	3,	4,	5,	-6,	


In [21]:
a - 1

-2,	-3,	2,	3,	4,	-7,	


In [22]:
b - 2

-4,	-6,	4,	6,	8,	-14,	


In [23]:
a -= 1
a

-2,	-3,	2,	3,	4,	-7,	


In [24]:
b -= 1
b

-3,	-5,	5,	7,	9,	-13,	


In [25]:
a -= b
a

1,	2,	-3,	-4,	-5,	6,	


## Multiplication

In [26]:
a = a * a
a

1,	4,	9,	16,	25,	36,	


In [27]:
a *= a
a

1,	16,	81,	256,	624.9999,	1296,	


In [28]:
a = a * 3
a

3,	48,	243,	768,	1875,	3888.001,	


In [29]:
a *= 3
a

9,	144,	729,	2304,	5624.999,	11664,	


### Divison

In [30]:
a

9,	144,	729,	2304,	5624.999,	11664,	


In [31]:
b

-3,	-5,	5,	7,	9,	-13,	


In [32]:
a = a/a
a

10,	145,	730,	2305,	5625.999,	11665,	


In [33]:
b / a

-0.3333333,	-0.03472222,	0.006858711,	0.003038194,	0.0016,	-0.00111454,	


In [34]:
a / b

-3,	-28.8,	145.8,	329.1428,	624.9999,	-897.231,	


In [35]:
a / 1

9,	144,	729,	2304,	5624.999,	11664,	


In [36]:
b / 1

-3,	-5,	5,	7,	9,	-13,	


In [37]:
a /= b
a

-3,	-28.8,	145.8,	329.1428,	624.9999,	-897.231,	


In [38]:
b /= a
b

1,	0.1736111,	0.03429355,	0.02126736,	0.0144,	0.01448902,	


In [39]:
a /= a
a

1,	1,	1,	1,	1,	1,	


In [40]:
b /= 1
b

1,	0.1736111,	0.03429355,	0.02126736,	0.0144,	0.01448902,	


In [41]:
b /= 2
b

0.5,	0.08680555,	0.01714678,	0.01063368,	0.007200001,	0.007244512,	


In [42]:
a *= 2

In [43]:
a

2,	2,	2,	2,	2,	2,	


In [44]:
a

2,	2,	2,	2,	2,	2,	


In [45]:
a **= 3

In [46]:
a

2,	2,	2,	2,	2,	2,	


In [47]:
a = a**2
a

64,	64,	64,	64,	64,	64,	
