In [1]:
from float_tensor import FloatTensor
import numpy as np

In [2]:
a = FloatTensor(np.array([[1,2,3,4,5],[2,3,4,5,6]]).astype('float'),autograd=True,keepgrads=True)
b = FloatTensor(np.array([[6,7,8,9,10],[11,12,13,14,15]]).astype('float').transpose(),autograd=True,keepgrads=True)
d = FloatTensor(np.ones((2,4)).astype('float'),autograd=True, keepgrads=True)

In [3]:
c = a.mm(b)
e = c.mm(d)

In [4]:
c

array([[ 130.,  205.],
       [ 170.,  270.]])

In [5]:
d

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
e

array([[ 335.,  335.,  335.,  335.],
       [ 440.,  440.,  440.,  440.]])

In [7]:
e.backward()

In [8]:
e.all_children_grads_accounted_for()

True

In [10]:
z = [2]
y = [3]
x = [2]

In [17]:
len(set(x+y+z))

2